spring:
  h2:
    console: 
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true 
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.web: ERROR
    com.quest: INFO

server:
  port: 8081